package coveragepublish

import (
	"strings"
)

// valueRow is one row of a coverage group's value matrix: the parameter
// value's label and kind, plus the live test keys currently covering it.
// An empty TestKeys means a gap. desiredGroupState builds these;
// renderDescription turns them into wiki markup.
type valueRow struct {
	Label    string
	Kind     string
	TestKeys []string
}

// gapMarker is the "Covered by" cell for a value with no live mapped test.
const gapMarker = "(none - gap)"

// renderDescription renders a coverage group's value matrix as Jira DC wiki
// markup -- Jira DC issue descriptions are wiki markup, not markdown, so the
// table uses ||header|| for the header row and |cell| for body rows -- then
// appends a generated-by footer naming the canonical requirement and version
// this Test Set was published from, so a reader in Jira knows the field is
// machine-managed and will be overwritten by the next publish.
func renderDescription(canonicalName, versionName, groupName string, rows []valueRow) string {
	var b strings.Builder

	b.WriteString("||Value||Kind||Covered by||\n")
	for _, r := range rows {
		coveredBy := gapMarker
		if len(r.TestKeys) > 0 {
			coveredBy = strings.Join(r.TestKeys, ", ")
		}
		b.WriteString("|")
		b.WriteString(r.Label)
		b.WriteString("|")
		b.WriteString(r.Kind)
		b.WriteString("|")
		b.WriteString(coveredBy)
		b.WriteString("|\n")
	}

	b.WriteString("\n----\n")
	b.WriteString("_Generated by Xray Test Manager's coverage publish for ")
	b.WriteString(canonicalName)
	b.WriteString(" - ")
	b.WriteString(versionName)
	b.WriteString(" / ")
	b.WriteString(groupName)
	b.WriteString(". This description is machine-managed and will be overwritten by the next publish._\n")

	return b.String()
}

// joinPublishedTests serializes a sorted test-key set into the newline-joined
// form coverage_group_publication.published_tests stores.
func joinPublishedTests(keys []string) string {
	return strings.Join(keys, "\n")
}

// splitPublishedTests is the inverse of joinPublishedTests. An empty column
// value must decode to zero keys, not a single-element slice holding an
// empty string -- strings.Split("", "\n") returns [""], which would read
// back as a phantom test key for a group with no mapped tests.
func splitPublishedTests(s string) []string {
	if s == "" {
		return nil
	}
	return strings.Split(s, "\n")
}
