// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {testrepo} from '../models';
import {main} from '../models';
import {syncer} from '../models';
import {profile} from '../models';
import {settings} from '../models';
import {jira} from '../models';

export function AddTestComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTestStep(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<testrepo.Step>;

export function AllocateTests(arg1:string,arg2:string,arg3:Array<string>):Promise<testrepo.AllocateResult>;

export function BulkAssociatePreconditions(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<testrepo.BulkEditResult>;

export function BulkAssociateRequirements(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<testrepo.BulkEditResult>;

export function BulkEditTests(arg1:string,arg2:Array<string>,arg3:testrepo.BulkEdit):Promise<testrepo.BulkEditResult>;

export function BulkMoveToFolder(arg1:string,arg2:Array<string>,arg3:string):Promise<testrepo.BulkEditResult>;

export function BulkReviewTests(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<testrepo.BulkEditResult>;

export function BulkSetTestRunStatus(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<testrepo.BulkEditResult>;

export function BulkTransitionTests(arg1:string,arg2:Array<string>,arg3:string):Promise<main.BulkTransitionResult>;

export function CheckJiraTestSteps(arg1:string,arg2:string):Promise<main.JiraStepInfo>;

export function CleanSampleData(arg1:string):Promise<number>;

export function CommitPendingChanges(arg1:string):Promise<syncer.CommitResult>;

export function CommitPendingChangesByIDs(arg1:string,arg2:Array<number>):Promise<syncer.CommitResult>;

export function CreateContainerAndAllocate(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<testrepo.CreateContainerResult>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<testrepo.Folder>;

export function CreatePrecondition(arg1:string,arg2:string):Promise<string>;

export function CreatePreconditionDetailed(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<profile.Profile>;

export function CreateProfileReusingToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<profile.Profile>;

export function CreateSavedView(arg1:string,arg2:string,arg3:string):Promise<testrepo.SavedView>;

export function CreateTest(arg1:string,arg2:testrepo.TestDraft):Promise<string>;

export function DeallocateTests(arg1:string,arg2:string,arg3:Array<string>):Promise<testrepo.DeallocateResult>;

export function DeleteContainer(arg1:string,arg2:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeletePrecondition(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSavedView(arg1:string,arg2:string):Promise<void>;

export function DeleteTestStep(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DiscardPendingChange(arg1:string,arg2:number):Promise<void>;

export function EditContainer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EditPreconditionField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestCustomField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestStepField(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ExportDiagnostics():Promise<string>;

export function ExportImportTemplate():Promise<string>;

export function ExportProfile(arg1:string):Promise<string>;

export function ExportPytest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportTests(arg1:string,arg2:testrepo.Query):Promise<string>;

export function GetBulkTransitionOptions(arg1:string,arg2:Array<string>):Promise<main.BulkTransitionOptions>;

export function GetContainerBoard(arg1:string,arg2:string):Promise<testrepo.TestPlanBoard>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetSettings():Promise<settings.Settings>;

export function GetStatistics(arg1:string):Promise<testrepo.Statistics>;

export function GetSyncState(arg1:string):Promise<testrepo.SyncState>;

export function GetTest(arg1:string,arg2:string):Promise<testrepo.TestCase>;

export function GetTestContainers(arg1:string,arg2:string):Promise<Array<testrepo.ContainerMembership>>;

export function GetTestCustomFields(arg1:string,arg2:string,arg3:boolean):Promise<Array<testrepo.CustomFieldValue>>;

export function GetTestMeta(arg1:string,arg2:string):Promise<jira.TestMeta>;

export function GetTestPreconditions(arg1:string,arg2:string):Promise<Array<testrepo.Precondition>>;

export function GetTestRequirements(arg1:string,arg2:string):Promise<Array<testrepo.Requirement>>;

export function GetTestReview(arg1:string,arg2:string):Promise<testrepo.Review>;

export function GetTestSteps(arg1:string,arg2:string,arg3:boolean):Promise<Array<testrepo.Step>>;

export function GetTestTransitions(arg1:string,arg2:string):Promise<Array<jira.Transition>>;

export function GetTraceabilitySankey(arg1:string,arg2:string,arg3:string):Promise<testrepo.Sankey>;

export function Health():Promise<main.HealthInfo>;

export function ImportProfile():Promise<profile.Profile>;

export function ImportTests(arg1:string,arg2:string,arg3:boolean,arg4:testrepo.ImportMapping,arg5:boolean):Promise<testrepo.ImportResult>;

export function ListAllPreconditions(arg1:string):Promise<Array<testrepo.Precondition>>;

export function ListAuditEntries(arg1:string,arg2:number):Promise<Array<testrepo.AuditEntry>>;

export function ListComponents(arg1:string):Promise<Array<testrepo.Bucket>>;

export function ListContainers(arg1:string,arg2:string):Promise<Array<testrepo.Container>>;

export function ListFolders(arg1:string):Promise<Array<testrepo.Folder>>;

export function ListMatchingKeys(arg1:string,arg2:testrepo.Query):Promise<Array<string>>;

export function ListPendingChanges(arg1:string):Promise<Array<testrepo.PendingChange>>;

export function ListPreconditionsWithUsage(arg1:string):Promise<Array<testrepo.PreconditionUsage>>;

export function ListPriorities(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListRequirementSources(arg1:string):Promise<Array<testrepo.RequirementSource>>;

export function ListRequirementsWithCoverage(arg1:string):Promise<Array<testrepo.RequirementCoverage>>;

export function ListSavedViews(arg1:string):Promise<Array<testrepo.SavedView>>;

export function ListStatuses(arg1:string):Promise<Array<string>>;

export function ListSyncLog(arg1:string,arg2:number):Promise<Array<testrepo.SyncLogEntry>>;

export function ListTests(arg1:string,arg2:testrepo.Query):Promise<testrepo.Page>;

export function ListTestsForPrecondition(arg1:string,arg2:string):Promise<Array<testrepo.PreconditionTest>>;

export function ListTestsForRequirement(arg1:string,arg2:string):Promise<Array<testrepo.RequirementTest>>;

export function MoveTestToFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PreviewImport(arg1:string,arg2:boolean):Promise<testrepo.ImportPreview>;

export function ReadLog(arg1:number):Promise<string>;

export function RemoveRequirementSource(arg1:string,arg2:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderTestSteps(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ResolveConflictKeepRemote(arg1:string,arg2:string):Promise<void>;

export function ResolveConflictOverride(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunStatuses():Promise<Array<string>>;

export function SeedSampleContainers(arg1:string):Promise<testrepo.SeedResult>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetRequirementSource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetTestPreconditions(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetTestRequirements(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetTestReview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetTestRunStatus(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SyncProfile(arg1:string):Promise<void>;

export function SyncProfileFull(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string):Promise<string>;

export function TransitionTest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<profile.Profile>;

export function UpdateProfileScope(arg1:string,arg2:string):Promise<void>;

export function UpdateProfileToken(arg1:string,arg2:string):Promise<void>;
