// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTestComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTestComment'](arg1, arg2, arg3);
}

export function AddTestStep(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTestStep'](arg1, arg2, arg3, arg4, arg5);
}

export function AllocateTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['AllocateTests'](arg1, arg2, arg3);
}

export function BulkAssociatePreconditions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkAssociatePreconditions'](arg1, arg2, arg3, arg4);
}

export function BulkEditTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkEditTests'](arg1, arg2, arg3);
}

export function BulkMoveToFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkMoveToFolder'](arg1, arg2, arg3);
}

export function BulkReviewTests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BulkReviewTests'](arg1, arg2, arg3, arg4, arg5);
}

export function BulkTransitionTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkTransitionTests'](arg1, arg2, arg3);
}

export function CheckJiraTestSteps(arg1, arg2) {
  return window['go']['main']['App']['CheckJiraTestSteps'](arg1, arg2);
}

export function CommitPendingChanges(arg1) {
  return window['go']['main']['App']['CommitPendingChanges'](arg1);
}

export function CommitPendingChangesByIDs(arg1, arg2) {
  return window['go']['main']['App']['CommitPendingChangesByIDs'](arg1, arg2);
}

export function CreateContainerAndAllocate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateContainerAndAllocate'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreatePrecondition(arg1, arg2) {
  return window['go']['main']['App']['CreatePrecondition'](arg1, arg2);
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateSavedView(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSavedView'](arg1, arg2, arg3);
}

export function DeallocateTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeallocateTests'](arg1, arg2, arg3);
}

export function DeleteContainer(arg1, arg2) {
  return window['go']['main']['App']['DeleteContainer'](arg1, arg2);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteSavedView(arg1, arg2) {
  return window['go']['main']['App']['DeleteSavedView'](arg1, arg2);
}

export function DeleteTestStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTestStep'](arg1, arg2, arg3);
}

export function DiscardPendingChange(arg1, arg2) {
  return window['go']['main']['App']['DiscardPendingChange'](arg1, arg2);
}

export function EditContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditContainer'](arg1, arg2, arg3);
}

export function EditPreconditionField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditPreconditionField'](arg1, arg2, arg3, arg4);
}

export function EditTestCustomField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTestCustomField'](arg1, arg2, arg3, arg4);
}

export function EditTestField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTestField'](arg1, arg2, arg3, arg4);
}

export function EditTestStepField(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EditTestStepField'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function ExportImportTemplate() {
  return window['go']['main']['App']['ExportImportTemplate']();
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function ExportPytest(arg1, arg2) {
  return window['go']['main']['App']['ExportPytest'](arg1, arg2);
}

export function ExportTests(arg1, arg2) {
  return window['go']['main']['App']['ExportTests'](arg1, arg2);
}

export function GetBulkTransitionOptions(arg1, arg2) {
  return window['go']['main']['App']['GetBulkTransitionOptions'](arg1, arg2);
}

export function GetContainerBoard(arg1, arg2) {
  return window['go']['main']['App']['GetContainerBoard'](arg1, arg2);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics(arg1) {
  return window['go']['main']['App']['GetStatistics'](arg1);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function GetTest(arg1, arg2) {
  return window['go']['main']['App']['GetTest'](arg1, arg2);
}

export function GetTestContainers(arg1, arg2) {
  return window['go']['main']['App']['GetTestContainers'](arg1, arg2);
}

export function GetTestCustomFields(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTestCustomFields'](arg1, arg2, arg3);
}

export function GetTestPreconditions(arg1, arg2) {
  return window['go']['main']['App']['GetTestPreconditions'](arg1, arg2);
}

export function GetTestReview(arg1, arg2) {
  return window['go']['main']['App']['GetTestReview'](arg1, arg2);
}

export function GetTestSteps(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTestSteps'](arg1, arg2, arg3);
}

export function GetTestTransitions(arg1, arg2) {
  return window['go']['main']['App']['GetTestTransitions'](arg1, arg2);
}

export function GetTraceabilitySankey(arg1) {
  return window['go']['main']['App']['GetTraceabilitySankey'](arg1);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportTests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportTests'](arg1, arg2, arg3, arg4, arg5);
}

export function ListAllPreconditions(arg1) {
  return window['go']['main']['App']['ListAllPreconditions'](arg1);
}

export function ListAuditEntries(arg1, arg2) {
  return window['go']['main']['App']['ListAuditEntries'](arg1, arg2);
}

export function ListComponents(arg1) {
  return window['go']['main']['App']['ListComponents'](arg1);
}

export function ListContainers(arg1, arg2) {
  return window['go']['main']['App']['ListContainers'](arg1, arg2);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListMatchingKeys(arg1, arg2) {
  return window['go']['main']['App']['ListMatchingKeys'](arg1, arg2);
}

export function ListPendingChanges(arg1) {
  return window['go']['main']['App']['ListPendingChanges'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListSavedViews(arg1) {
  return window['go']['main']['App']['ListSavedViews'](arg1);
}

export function ListSyncLog(arg1, arg2) {
  return window['go']['main']['App']['ListSyncLog'](arg1, arg2);
}

export function ListTests(arg1, arg2) {
  return window['go']['main']['App']['ListTests'](arg1, arg2);
}

export function MoveTestToFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveTestToFolder'](arg1, arg2, arg3);
}

export function PreviewImport(arg1, arg2) {
  return window['go']['main']['App']['PreviewImport'](arg1, arg2);
}

export function ReadLog(arg1) {
  return window['go']['main']['App']['ReadLog'](arg1);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function ReorderTestSteps(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderTestSteps'](arg1, arg2, arg3);
}

export function ResolveConflictKeepRemote(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflictKeepRemote'](arg1, arg2);
}

export function ResolveConflictOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflictOverride'](arg1, arg2, arg3);
}

export function SeedSampleContainers(arg1) {
  return window['go']['main']['App']['SeedSampleContainers'](arg1);
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function SetTestPreconditions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTestPreconditions'](arg1, arg2, arg3);
}

export function SetTestReview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetTestReview'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SyncProfile(arg1) {
  return window['go']['main']['App']['SyncProfile'](arg1);
}

export function SyncProfileFull(arg1) {
  return window['go']['main']['App']['SyncProfileFull'](arg1);
}

export function TestConnection(arg1, arg2) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2);
}

export function TransitionTest(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransitionTest'](arg1, arg2, arg3);
}

export function UpdateProfileScope(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileScope'](arg1, arg2);
}

export function UpdateProfileToken(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileToken'](arg1, arg2);
}
