// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCalledTestStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddCalledTestStep'](arg1, arg2, arg3);
}

export function AddConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['AddConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function AddTestComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddTestComment'](arg1, arg2, arg3);
}

export function AddTestStep(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddTestStep'](arg1, arg2, arg3, arg4, arg5);
}

export function AllocateTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['AllocateTests'](arg1, arg2, arg3);
}

export function AnalyzeGap(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AnalyzeGap'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AnalyzeJUnitImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeJUnitImport'](arg1, arg2, arg3);
}

export function AnalyzeJUnitImportNewExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeJUnitImportNewExec'](arg1, arg2, arg3);
}

export function AnalyzeRequirementImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['AnalyzeRequirementImport'](arg1, arg2, arg3);
}

export function ApplyJUnitImport(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyJUnitImport'](arg1, arg2, arg3);
}

export function ApplyJUnitImportNewExec(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyJUnitImportNewExec'](arg1, arg2, arg3);
}

export function BulkAssociatePreconditions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkAssociatePreconditions'](arg1, arg2, arg3, arg4);
}

export function BulkAssociateRequirements(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkAssociateRequirements'](arg1, arg2, arg3, arg4);
}

export function BulkEditContainers(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkEditContainers'](arg1, arg2, arg3);
}

export function BulkEditTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkEditTests'](arg1, arg2, arg3);
}

export function BulkMoveToFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkMoveToFolder'](arg1, arg2, arg3);
}

export function BulkReplacePreconditions(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkReplacePreconditions'](arg1, arg2, arg3, arg4);
}

export function BulkReplaceRequirements(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkReplaceRequirements'](arg1, arg2, arg3, arg4);
}

export function BulkReviewTests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['BulkReviewTests'](arg1, arg2, arg3, arg4, arg5);
}

export function BulkSetTestRunStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BulkSetTestRunStatus'](arg1, arg2, arg3, arg4);
}

export function BulkTransitionTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['BulkTransitionTests'](arg1, arg2, arg3);
}

export function ChangeTestType(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeTestType'](arg1, arg2, arg3);
}

export function CheckJiraTestSteps(arg1, arg2) {
  return window['go']['main']['App']['CheckJiraTestSteps'](arg1, arg2);
}

export function CleanSampleData(arg1) {
  return window['go']['main']['App']['CleanSampleData'](arg1);
}

export function CloneTest(arg1, arg2) {
  return window['go']['main']['App']['CloneTest'](arg1, arg2);
}

export function CloneTestSteps(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneTestSteps'](arg1, arg2, arg3, arg4);
}

export function CloneVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CloneVersion'](arg1, arg2, arg3, arg4);
}

export function CommitPendingChanges(arg1) {
  return window['go']['main']['App']['CommitPendingChanges'](arg1);
}

export function CommitPendingChangesByIDs(arg1, arg2) {
  return window['go']['main']['App']['CommitPendingChangesByIDs'](arg1, arg2);
}

export function ComputeBridgeGap(arg1, arg2) {
  return window['go']['main']['App']['ComputeBridgeGap'](arg1, arg2);
}

export function CreateBugForTest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateBugForTest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateCanonicalRequirement(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCanonicalRequirement'](arg1, arg2, arg3, arg4);
}

export function CreateChangeRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateChangeRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateContainerAndAllocate(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateContainerAndAllocate'](arg1, arg2, arg3, arg4);
}

export function CreateFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateFolder'](arg1, arg2, arg3);
}

export function CreatePrecondition(arg1, arg2) {
  return window['go']['main']['App']['CreatePrecondition'](arg1, arg2);
}

export function CreatePreconditionDetailed(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreatePreconditionDetailed'](arg1, arg2, arg3, arg4);
}

export function CreateProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['CreateProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function CreateProfileReusingToken(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['CreateProfileReusingToken'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function CreateRequirement(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateRequirement'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateSavedView(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateSavedView'](arg1, arg2, arg3);
}

export function CreateTest(arg1, arg2) {
  return window['go']['main']['App']['CreateTest'](arg1, arg2);
}

export function CreateTestsFromGaps(arg1, arg2) {
  return window['go']['main']['App']['CreateTestsFromGaps'](arg1, arg2);
}

export function CreateVersion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateVersion'](arg1, arg2, arg3, arg4, arg5);
}

export function DeallocateTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeallocateTests'](arg1, arg2, arg3);
}

export function DeleteCanonicalRequirement(arg1, arg2) {
  return window['go']['main']['App']['DeleteCanonicalRequirement'](arg1, arg2);
}

export function DeleteChangeRequest(arg1, arg2) {
  return window['go']['main']['App']['DeleteChangeRequest'](arg1, arg2);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteContainer(arg1, arg2) {
  return window['go']['main']['App']['DeleteContainer'](arg1, arg2);
}

export function DeleteCoverageNode(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCoverageNode'](arg1, arg2, arg3);
}

export function DeleteFolder(arg1, arg2) {
  return window['go']['main']['App']['DeleteFolder'](arg1, arg2);
}

export function DeletePrecondition(arg1, arg2) {
  return window['go']['main']['App']['DeletePrecondition'](arg1, arg2);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DeleteRequirement(arg1, arg2) {
  return window['go']['main']['App']['DeleteRequirement'](arg1, arg2);
}

export function DeleteSavedView(arg1, arg2) {
  return window['go']['main']['App']['DeleteSavedView'](arg1, arg2);
}

export function DeleteTestStep(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteTestStep'](arg1, arg2, arg3);
}

export function DeleteVersion(arg1, arg2) {
  return window['go']['main']['App']['DeleteVersion'](arg1, arg2);
}

export function DetectStaleCoverageMappings(arg1, arg2) {
  return window['go']['main']['App']['DetectStaleCoverageMappings'](arg1, arg2);
}

export function DiscardAllPendingChanges(arg1) {
  return window['go']['main']['App']['DiscardAllPendingChanges'](arg1);
}

export function DiscardPendingChange(arg1, arg2) {
  return window['go']['main']['App']['DiscardPendingChange'](arg1, arg2);
}

export function DownloadCoverageTemplate() {
  return window['go']['main']['App']['DownloadCoverageTemplate']();
}

export function EditContainer(arg1, arg2, arg3) {
  return window['go']['main']['App']['EditContainer'](arg1, arg2, arg3);
}

export function EditPreconditionField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditPreconditionField'](arg1, arg2, arg3, arg4);
}

export function EditRequirementField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditRequirementField'](arg1, arg2, arg3, arg4);
}

export function EditTestCustomField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTestCustomField'](arg1, arg2, arg3, arg4);
}

export function EditTestField(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EditTestField'](arg1, arg2, arg3, arg4);
}

export function EditTestStepField(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['EditTestStepField'](arg1, arg2, arg3, arg4, arg5);
}

export function ExcludeFromDuplicates(arg1, arg2) {
  return window['go']['main']['App']['ExcludeFromDuplicates'](arg1, arg2);
}

export function ExportBugsWithRunHistory(arg1, arg2) {
  return window['go']['main']['App']['ExportBugsWithRunHistory'](arg1, arg2);
}

export function ExportCoverageReport(arg1, arg2) {
  return window['go']['main']['App']['ExportCoverageReport'](arg1, arg2);
}

export function ExportDashboard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExportDashboard'](arg1, arg2, arg3, arg4);
}

export function ExportDiagnostics() {
  return window['go']['main']['App']['ExportDiagnostics']();
}

export function ExportGapReport(arg1, arg2) {
  return window['go']['main']['App']['ExportGapReport'](arg1, arg2);
}

export function ExportImportTemplate() {
  return window['go']['main']['App']['ExportImportTemplate']();
}

export function ExportProfile(arg1) {
  return window['go']['main']['App']['ExportProfile'](arg1);
}

export function ExportPytest(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportPytest'](arg1, arg2, arg3);
}

export function ExportRequirementAudit(arg1) {
  return window['go']['main']['App']['ExportRequirementAudit'](arg1);
}

export function ExportRequirementImportTemplate() {
  return window['go']['main']['App']['ExportRequirementImportTemplate']();
}

export function ExportSummaryFolderTemplate() {
  return window['go']['main']['App']['ExportSummaryFolderTemplate']();
}

export function ExportSummaryTemplate() {
  return window['go']['main']['App']['ExportSummaryTemplate']();
}

export function ExportTests(arg1, arg2) {
  return window['go']['main']['App']['ExportTests'](arg1, arg2);
}

export function ExportTraceability(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['ExportTraceability'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function GetBridgeMapping(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBridgeMapping'](arg1, arg2, arg3);
}

export function GetBugCreateFields(arg1) {
  return window['go']['main']['App']['GetBugCreateFields'](arg1);
}

export function GetBugDetail(arg1, arg2) {
  return window['go']['main']['App']['GetBugDetail'](arg1, arg2);
}

export function GetBulkTransitionOptions(arg1, arg2) {
  return window['go']['main']['App']['GetBulkTransitionOptions'](arg1, arg2);
}

export function GetCRAdoption(arg1, arg2) {
  return window['go']['main']['App']['GetCRAdoption'](arg1, arg2);
}

export function GetCRImpact(arg1, arg2) {
  return window['go']['main']['App']['GetCRImpact'](arg1, arg2);
}

export function GetCapabilities(arg1) {
  return window['go']['main']['App']['GetCapabilities'](arg1);
}

export function GetContainerBoard(arg1, arg2) {
  return window['go']['main']['App']['GetContainerBoard'](arg1, arg2);
}

export function GetCoverageProjectStatus(arg1) {
  return window['go']['main']['App']['GetCoverageProjectStatus'](arg1);
}

export function GetCoveragePublishStatus(arg1, arg2) {
  return window['go']['main']['App']['GetCoveragePublishStatus'](arg1, arg2);
}

export function GetCoverageRelationSankey(arg1) {
  return window['go']['main']['App']['GetCoverageRelationSankey'](arg1);
}

export function GetCoverageReport(arg1, arg2) {
  return window['go']['main']['App']['GetCoverageReport'](arg1, arg2);
}

export function GetDiagnostics() {
  return window['go']['main']['App']['GetDiagnostics']();
}

export function GetExecutionMembersWithRuns(arg1, arg2) {
  return window['go']['main']['App']['GetExecutionMembersWithRuns'](arg1, arg2);
}

export function GetExecutionsForPlans(arg1, arg2) {
  return window['go']['main']['App']['GetExecutionsForPlans'](arg1, arg2);
}

export function GetParamModel(arg1, arg2) {
  return window['go']['main']['App']['GetParamModel'](arg1, arg2);
}

export function GetProfileProjectKey(arg1) {
  return window['go']['main']['App']['GetProfileProjectKey'](arg1);
}

export function GetRequirementLinks(arg1, arg2) {
  return window['go']['main']['App']['GetRequirementLinks'](arg1, arg2);
}

export function GetRequirementTraceability(arg1, arg2) {
  return window['go']['main']['App']['GetRequirementTraceability'](arg1, arg2);
}

export function GetRunRollup(arg1, arg2) {
  return window['go']['main']['App']['GetRunRollup'](arg1, arg2);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStatistics(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetStatistics'](arg1, arg2, arg3, arg4);
}

export function GetSubTaskTraceability(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSubTaskTraceability'](arg1, arg2, arg3);
}

export function GetSyncState(arg1) {
  return window['go']['main']['App']['GetSyncState'](arg1);
}

export function GetTest(arg1, arg2) {
  return window['go']['main']['App']['GetTest'](arg1, arg2);
}

export function GetTestBugs(arg1, arg2) {
  return window['go']['main']['App']['GetTestBugs'](arg1, arg2);
}

export function GetTestContainers(arg1, arg2) {
  return window['go']['main']['App']['GetTestContainers'](arg1, arg2);
}

export function GetTestCustomFields(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTestCustomFields'](arg1, arg2, arg3);
}

export function GetTestMeta(arg1, arg2) {
  return window['go']['main']['App']['GetTestMeta'](arg1, arg2);
}

export function GetTestPreconditions(arg1, arg2) {
  return window['go']['main']['App']['GetTestPreconditions'](arg1, arg2);
}

export function GetTestRequirements(arg1, arg2) {
  return window['go']['main']['App']['GetTestRequirements'](arg1, arg2);
}

export function GetTestReview(arg1, arg2) {
  return window['go']['main']['App']['GetTestReview'](arg1, arg2);
}

export function GetTestRunHistory(arg1, arg2) {
  return window['go']['main']['App']['GetTestRunHistory'](arg1, arg2);
}

export function GetTestSteps(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTestSteps'](arg1, arg2, arg3);
}

export function GetTestTransitions(arg1, arg2) {
  return window['go']['main']['App']['GetTestTransitions'](arg1, arg2);
}

export function GetTraceabilitySankey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetTraceabilitySankey'](arg1, arg2, arg3, arg4);
}

export function GetVersionDistribution(arg1, arg2) {
  return window['go']['main']['App']['GetVersionDistribution'](arg1, arg2);
}

export function Health() {
  return window['go']['main']['App']['Health']();
}

export function ImportCoverageTemplate(arg1, arg2) {
  return window['go']['main']['App']['ImportCoverageTemplate'](arg1, arg2);
}

export function ImportProfile() {
  return window['go']['main']['App']['ImportProfile']();
}

export function ImportRequirements(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportRequirements'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportTests(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ImportTests'](arg1, arg2, arg3, arg4, arg5);
}

export function LinkExistingBugToRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['LinkExistingBugToRun'](arg1, arg2, arg3, arg4);
}

export function ListAllPreconditions(arg1) {
  return window['go']['main']['App']['ListAllPreconditions'](arg1);
}

export function ListAuditEntries(arg1, arg2) {
  return window['go']['main']['App']['ListAuditEntries'](arg1, arg2);
}

export function ListBugsForContainer(arg1, arg2) {
  return window['go']['main']['App']['ListBugsForContainer'](arg1, arg2);
}

export function ListBugsWithTests(arg1) {
  return window['go']['main']['App']['ListBugsWithTests'](arg1);
}

export function ListCanonicalRequirements(arg1) {
  return window['go']['main']['App']['ListCanonicalRequirements'](arg1);
}

export function ListCanonicalReuse(arg1, arg2) {
  return window['go']['main']['App']['ListCanonicalReuse'](arg1, arg2);
}

export function ListChangeRequests(arg1, arg2) {
  return window['go']['main']['App']['ListChangeRequests'](arg1, arg2);
}

export function ListComponents(arg1) {
  return window['go']['main']['App']['ListComponents'](arg1);
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function ListContainers(arg1, arg2) {
  return window['go']['main']['App']['ListContainers'](arg1, arg2);
}

export function ListCoverageCandidateTests(arg1, arg2) {
  return window['go']['main']['App']['ListCoverageCandidateTests'](arg1, arg2);
}

export function ListCoverageGaps(arg1, arg2) {
  return window['go']['main']['App']['ListCoverageGaps'](arg1, arg2);
}

export function ListCoverageProjects(arg1) {
  return window['go']['main']['App']['ListCoverageProjects'](arg1);
}

export function ListFolders(arg1) {
  return window['go']['main']['App']['ListFolders'](arg1);
}

export function ListMatchingKeys(arg1, arg2) {
  return window['go']['main']['App']['ListMatchingKeys'](arg1, arg2);
}

export function ListPendingChanges(arg1) {
  return window['go']['main']['App']['ListPendingChanges'](arg1);
}

export function ListPreconditionsWithUsage(arg1) {
  return window['go']['main']['App']['ListPreconditionsWithUsage'](arg1);
}

export function ListPriorities(arg1) {
  return window['go']['main']['App']['ListPriorities'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListProjectComponents(arg1, arg2) {
  return window['go']['main']['App']['ListProjectComponents'](arg1, arg2);
}

export function ListProjectFixVersions(arg1, arg2) {
  return window['go']['main']['App']['ListProjectFixVersions'](arg1, arg2);
}

export function ListRequirementLinkTypeDetails(arg1) {
  return window['go']['main']['App']['ListRequirementLinkTypeDetails'](arg1);
}

export function ListRequirementSources(arg1) {
  return window['go']['main']['App']['ListRequirementSources'](arg1);
}

export function ListRequirementsWithCoverage(arg1) {
  return window['go']['main']['App']['ListRequirementsWithCoverage'](arg1);
}

export function ListSavedViews(arg1) {
  return window['go']['main']['App']['ListSavedViews'](arg1);
}

export function ListStatuses(arg1) {
  return window['go']['main']['App']['ListStatuses'](arg1);
}

export function ListSyncLog(arg1, arg2) {
  return window['go']['main']['App']['ListSyncLog'](arg1, arg2);
}

export function ListTestCallLinks(arg1) {
  return window['go']['main']['App']['ListTestCallLinks'](arg1);
}

export function ListTests(arg1, arg2) {
  return window['go']['main']['App']['ListTests'](arg1, arg2);
}

export function ListTestsForBug(arg1, arg2) {
  return window['go']['main']['App']['ListTestsForBug'](arg1, arg2);
}

export function ListTestsForPrecondition(arg1, arg2) {
  return window['go']['main']['App']['ListTestsForPrecondition'](arg1, arg2);
}

export function ListTestsForRequirement(arg1, arg2) {
  return window['go']['main']['App']['ListTestsForRequirement'](arg1, arg2);
}

export function ListValueTests(arg1, arg2) {
  return window['go']['main']['App']['ListValueTests'](arg1, arg2);
}

export function ListVersions(arg1, arg2) {
  return window['go']['main']['App']['ListVersions'](arg1, arg2);
}

export function MoveTestToFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoveTestToFolder'](arg1, arg2, arg3);
}

export function PreviewImport(arg1, arg2) {
  return window['go']['main']['App']['PreviewImport'](arg1, arg2);
}

export function PublishCoverageGroups(arg1, arg2) {
  return window['go']['main']['App']['PublishCoverageGroups'](arg1, arg2);
}

export function PublishToTarget(arg1, arg2, arg3) {
  return window['go']['main']['App']['PublishToTarget'](arg1, arg2, arg3);
}

export function ReadLog(arg1) {
  return window['go']['main']['App']['ReadLog'](arg1);
}

export function RecreateDeletedTest(arg1, arg2) {
  return window['go']['main']['App']['RecreateDeletedTest'](arg1, arg2);
}

export function RemoveRequirementSource(arg1, arg2) {
  return window['go']['main']['App']['RemoveRequirementSource'](arg1, arg2);
}

export function RenameCanonicalRequirement(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameCanonicalRequirement'](arg1, arg2, arg3, arg4, arg5);
}

export function RenameFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameFolder'](arg1, arg2, arg3);
}

export function RenameVersion(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RenameVersion'](arg1, arg2, arg3, arg4, arg5);
}

export function ReorderTestSteps(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderTestSteps'](arg1, arg2, arg3);
}

export function ResolveConflictKeepRemote(arg1, arg2) {
  return window['go']['main']['App']['ResolveConflictKeepRemote'](arg1, arg2);
}

export function ResolveConflictMerge(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResolveConflictMerge'](arg1, arg2, arg3, arg4);
}

export function ResolveConflictOverride(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveConflictOverride'](arg1, arg2, arg3);
}

export function RunStatuses() {
  return window['go']['main']['App']['RunStatuses']();
}

export function SaveBridgeMapping(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBridgeMapping'](arg1, arg2, arg3, arg4);
}

export function ScanAllDuplicateSteps(arg1) {
  return window['go']['main']['App']['ScanAllDuplicateSteps'](arg1);
}

export function ScanDuplicateGroupSteps(arg1, arg2) {
  return window['go']['main']['App']['ScanDuplicateGroupSteps'](arg1, arg2);
}

export function ScanDuplicates(arg1) {
  return window['go']['main']['App']['ScanDuplicates'](arg1);
}

export function SeedDemoCoverageExample(arg1) {
  return window['go']['main']['App']['SeedDemoCoverageExample'](arg1);
}

export function SeedEUICCReference(arg1) {
  return window['go']['main']['App']['SeedEUICCReference'](arg1);
}

export function SeedPKCS11Reference(arg1) {
  return window['go']['main']['App']['SeedPKCS11Reference'](arg1);
}

export function SeedSampleContainers(arg1) {
  return window['go']['main']['App']['SeedSampleContainers'](arg1);
}

export function SetCRDecision(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetCRDecision'](arg1, arg2, arg3, arg4, arg5);
}

export function SetCanonicalMembers(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCanonicalMembers'](arg1, arg2, arg3);
}

export function SetContainerEnvironments(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetContainerEnvironments'](arg1, arg2, arg3);
}

export function SetCoverageProjects(arg1, arg2) {
  return window['go']['main']['App']['SetCoverageProjects'](arg1, arg2);
}

export function SetDefaultProfile(arg1) {
  return window['go']['main']['App']['SetDefaultProfile'](arg1);
}

export function SetMemberVersion(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetMemberVersion'](arg1, arg2, arg3, arg4);
}

export function SetRequirementLinkType(arg1) {
  return window['go']['main']['App']['SetRequirementLinkType'](arg1);
}

export function SetRequirementLinks(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRequirementLinks'](arg1, arg2, arg3, arg4);
}

export function SetRequirementSource(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetRequirementSource'](arg1, arg2, arg3, arg4);
}

export function SetShowCoverage(arg1) {
  return window['go']['main']['App']['SetShowCoverage'](arg1);
}

export function SetTestPreconditions(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTestPreconditions'](arg1, arg2, arg3);
}

export function SetTestRequirements(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetTestRequirements'](arg1, arg2, arg3);
}

export function SetTestReview(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetTestReview'](arg1, arg2, arg3, arg4, arg5);
}

export function SetTestRunComment(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTestRunComment'](arg1, arg2, arg3, arg4);
}

export function SetTestRunStatus(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTestRunStatus'](arg1, arg2, arg3, arg4);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetValueTests(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetValueTests'](arg1, arg2, arg3);
}

export function SetVersionStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetVersionStatus'](arg1, arg2, arg3);
}

export function SyncBugs(arg1) {
  return window['go']['main']['App']['SyncBugs'](arg1);
}

export function SyncContainers(arg1) {
  return window['go']['main']['App']['SyncContainers'](arg1);
}

export function SyncProfile(arg1) {
  return window['go']['main']['App']['SyncProfile'](arg1);
}

export function SyncProfileFull(arg1) {
  return window['go']['main']['App']['SyncProfileFull'](arg1);
}

export function SyncRequirements(arg1) {
  return window['go']['main']['App']['SyncRequirements'](arg1);
}

export function SyncTestCalls(arg1) {
  return window['go']['main']['App']['SyncTestCalls'](arg1);
}

export function SyncTests(arg1) {
  return window['go']['main']['App']['SyncTests'](arg1);
}

export function TestConnection(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TestConnection'](arg1, arg2, arg3, arg4, arg5);
}

export function TestProfileConnection(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TestProfileConnection'](arg1, arg2, arg3, arg4);
}

export function TransitionTest(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransitionTest'](arg1, arg2, arg3);
}

export function UnexcludeFromDuplicates(arg1, arg2) {
  return window['go']['main']['App']['UnexcludeFromDuplicates'](arg1, arg2);
}

export function UnlinkBugFromRun(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnlinkBugFromRun'](arg1, arg2, arg3, arg4);
}

export function UpdateChangeRequest(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['UpdateChangeRequest'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateConnection(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13) {
  return window['go']['main']['App']['UpdateConnection'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13);
}

export function UpdateProfile(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12);
}

export function UpdateProfileScope(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileScope'](arg1, arg2);
}

export function UpdateProfileToken(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileToken'](arg1, arg2);
}

export function UpsertCoverageNode(arg1, arg2) {
  return window['go']['main']['App']['UpsertCoverageNode'](arg1, arg2);
}
