// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {testrepo} from '../models';
import {main} from '../models';
import {syncer} from '../models';
import {profile} from '../models';
import {coverage} from '../models';
import {jira} from '../models';
import {settings} from '../models';

export function AddCalledTestStep(arg1:string,arg2:string,arg3:string):Promise<testrepo.Step>;

export function AddTestComment(arg1:string,arg2:string,arg3:string):Promise<void>;

export function AddTestStep(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<testrepo.Step>;

export function AllocateTests(arg1:string,arg2:string,arg3:Array<string>):Promise<testrepo.AllocateResult>;

export function AnalyzeGap(arg1:string,arg2:string,arg3:string,arg4:boolean,arg5:string,arg6:boolean,arg7:boolean,arg8:boolean):Promise<testrepo.GapResult>;

export function AnalyzeJUnitImport(arg1:string,arg2:string,arg3:string):Promise<testrepo.JUnitImportPreview>;

export function AnalyzeJUnitImportNewExec(arg1:string,arg2:string,arg3:boolean):Promise<testrepo.JUnitNewExecPreview>;

export function AnalyzeRequirementImport(arg1:string,arg2:string,arg3:boolean):Promise<testrepo.RequirementImportPreview>;

export function ApplyJUnitImport(arg1:string,arg2:string,arg3:Array<testrepo.JUnitMatch>):Promise<testrepo.BulkEditResult>;

export function ApplyJUnitImportNewExec(arg1:string,arg2:string,arg3:Array<testrepo.JUnitNewExecRow>):Promise<testrepo.JUnitNewExecResult>;

export function BulkAssociatePreconditions(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<testrepo.BulkEditResult>;

export function BulkAssociateRequirements(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<testrepo.BulkEditResult>;

export function BulkEditContainers(arg1:string,arg2:Array<string>,arg3:testrepo.BulkEdit):Promise<testrepo.BulkEditResult>;

export function BulkEditTests(arg1:string,arg2:Array<string>,arg3:testrepo.BulkEdit):Promise<testrepo.BulkEditResult>;

export function BulkMoveToFolder(arg1:string,arg2:Array<string>,arg3:string):Promise<testrepo.BulkEditResult>;

export function BulkReplacePreconditions(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>):Promise<testrepo.BulkEditResult>;

export function BulkReplaceRequirements(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:Array<string>):Promise<testrepo.BulkEditResult>;

export function BulkReviewTests(arg1:string,arg2:Array<string>,arg3:string,arg4:string,arg5:string):Promise<testrepo.BulkEditResult>;

export function BulkSetTestRunStatus(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<testrepo.BulkEditResult>;

export function BulkTransitionTests(arg1:string,arg2:Array<string>,arg3:string):Promise<main.BulkTransitionResult>;

export function CheckJiraTestSteps(arg1:string,arg2:string):Promise<main.JiraStepInfo>;

export function CleanSampleData(arg1:string):Promise<number>;

export function CloneTest(arg1:string,arg2:string):Promise<string>;

export function CloneTestSteps(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<Array<testrepo.Step>>;

export function CloneVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CommitPendingChanges(arg1:string):Promise<syncer.CommitResult>;

export function CommitPendingChangesByIDs(arg1:string,arg2:Array<number>):Promise<syncer.CommitResult>;

export function CreateBugForTest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:Array<string>,arg8:Record<string, any>):Promise<string>;

export function CreateCanonicalRequirement(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateChangeRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function CreateContainerAndAllocate(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<testrepo.CreateContainerResult>;

export function CreateFolder(arg1:string,arg2:string,arg3:string):Promise<testrepo.Folder>;

export function CreatePrecondition(arg1:string,arg2:string):Promise<string>;

export function CreatePreconditionDetailed(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function CreateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:boolean):Promise<profile.Profile>;

export function CreateProfileReusingToken(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<profile.Profile>;

export function CreateRequirement(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<string>;

export function CreateSavedView(arg1:string,arg2:string,arg3:string):Promise<testrepo.SavedView>;

export function CreateTest(arg1:string,arg2:testrepo.TestDraft):Promise<string>;

export function CreateTestsFromGaps(arg1:string,arg2:Array<testrepo.GapTest>):Promise<testrepo.ImportResult>;

export function CreateVersion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function DeallocateTests(arg1:string,arg2:string,arg3:Array<string>):Promise<testrepo.DeallocateResult>;

export function DeleteCanonicalRequirement(arg1:string,arg2:string):Promise<void>;

export function DeleteChangeRequest(arg1:string,arg2:string):Promise<void>;

export function DeleteContainer(arg1:string,arg2:string):Promise<void>;

export function DeleteCoverageNode(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteFolder(arg1:string,arg2:string):Promise<void>;

export function DeletePrecondition(arg1:string,arg2:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteRequirement(arg1:string,arg2:string):Promise<void>;

export function DeleteSavedView(arg1:string,arg2:string):Promise<void>;

export function DeleteTestStep(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteVersion(arg1:string,arg2:string):Promise<void>;

export function DetectStaleCoverageMappings(arg1:string,arg2:string):Promise<Array<coverage.StaleMapping>>;

export function DiscardAllPendingChanges(arg1:string):Promise<number>;

export function DiscardPendingChange(arg1:string,arg2:number):Promise<void>;

export function DownloadCoverageTemplate():Promise<string>;

export function EditContainer(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EditPreconditionField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditRequirementField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestCustomField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestField(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function EditTestStepField(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ExcludeFromDuplicates(arg1:string,arg2:string):Promise<void>;

export function ExportBugsWithRunHistory(arg1:string,arg2:Array<string>):Promise<string>;

export function ExportCoverageReport(arg1:string,arg2:string):Promise<string>;

export function ExportDashboard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function ExportDiagnostics():Promise<string>;

export function ExportGapReport(arg1:testrepo.GapResult,arg2:string):Promise<string>;

export function ExportImportTemplate():Promise<string>;

export function ExportProfile(arg1:string):Promise<string>;

export function ExportPytest(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportRequirementAudit(arg1:string):Promise<string>;

export function ExportRequirementImportTemplate():Promise<string>;

export function ExportSummaryFolderTemplate():Promise<string>;

export function ExportSummaryTemplate():Promise<string>;

export function ExportTests(arg1:string,arg2:testrepo.Query):Promise<string>;

export function ExportTraceability(arg1:string,arg2:string,arg3:Array<string>,arg4:Array<string>,arg5:boolean,arg6:Array<string>,arg7:Array<string>):Promise<string>;

export function GetBugCreateFields(arg1:string):Promise<Array<jira.BugCreateField>>;

export function GetBugDetail(arg1:string,arg2:string):Promise<jira.BugDetail>;

export function GetBulkTransitionOptions(arg1:string,arg2:Array<string>):Promise<main.BulkTransitionOptions>;

export function GetCRAdoption(arg1:string,arg2:string):Promise<Array<coverage.CRShare>>;

export function GetCRImpact(arg1:string,arg2:string):Promise<coverage.CRImpactResult>;

export function GetContainerBoard(arg1:string,arg2:string):Promise<testrepo.TestPlanBoard>;

export function GetCoverageProjectStatus(arg1:string):Promise<Array<coverage.ProjectCoverageRow>>;

export function GetCoverageRelationSankey(arg1:string):Promise<testrepo.Sankey>;

export function GetCoverageReport(arg1:string,arg2:string):Promise<coverage.CoverageReport>;

export function GetDiagnostics():Promise<main.Diagnostics>;

export function GetExecutionMembersWithRuns(arg1:string,arg2:string):Promise<Array<testrepo.ExecMemberRun>>;

export function GetExecutionsForPlans(arg1:string,arg2:Array<string>):Promise<Array<testrepo.Container>>;

export function GetParamModel(arg1:string,arg2:string):Promise<coverage.ParamModel>;

export function GetProfileProjectKey(arg1:string):Promise<string>;

export function GetRequirementLinks(arg1:string,arg2:string):Promise<Array<testrepo.ReqReqLink>>;

export function GetRequirementTraceability(arg1:string,arg2:Array<string>):Promise<testrepo.Sankey>;

export function GetRunRollup(arg1:string,arg2:string):Promise<testrepo.RunRollup>;

export function GetSettings():Promise<settings.Settings>;

export function GetStatistics(arg1:string,arg2:string,arg3:string,arg4:string):Promise<testrepo.Statistics>;

export function GetSubTaskTraceability(arg1:string,arg2:Array<string>,arg3:boolean):Promise<testrepo.Sankey>;

export function GetSyncState(arg1:string):Promise<testrepo.SyncState>;

export function GetTest(arg1:string,arg2:string):Promise<testrepo.TestCase>;

export function GetTestBugs(arg1:string,arg2:string):Promise<Array<testrepo.TestBug>>;

export function GetTestContainers(arg1:string,arg2:string):Promise<Array<testrepo.ContainerMembership>>;

export function GetTestCustomFields(arg1:string,arg2:string,arg3:boolean):Promise<Array<testrepo.CustomFieldValue>>;

export function GetTestMeta(arg1:string,arg2:string):Promise<jira.TestMeta>;

export function GetTestPreconditions(arg1:string,arg2:string):Promise<Array<testrepo.Precondition>>;

export function GetTestRequirements(arg1:string,arg2:string):Promise<Array<testrepo.Requirement>>;

export function GetTestReview(arg1:string,arg2:string):Promise<testrepo.Review>;

export function GetTestRunHistory(arg1:string,arg2:string):Promise<Array<testrepo.TestRunEntry>>;

export function GetTestSteps(arg1:string,arg2:string,arg3:boolean):Promise<Array<testrepo.Step>>;

export function GetTestTransitions(arg1:string,arg2:string):Promise<Array<jira.Transition>>;

export function GetTraceabilitySankey(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<testrepo.Sankey>;

export function GetVersionDistribution(arg1:string,arg2:string):Promise<Array<coverage.VersionShare>>;

export function Health():Promise<main.HealthInfo>;

export function ImportCoverageTemplate(arg1:string,arg2:string):Promise<coverage.ImportSummary>;

export function ImportProfile():Promise<profile.Profile>;

export function ImportRequirements(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<testrepo.RequirementImportResult>;

export function ImportTests(arg1:string,arg2:string,arg3:boolean,arg4:testrepo.ImportMapping,arg5:boolean):Promise<testrepo.ImportResult>;

export function LinkExistingBugToRun(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ListAllPreconditions(arg1:string):Promise<Array<testrepo.Precondition>>;

export function ListAuditEntries(arg1:string,arg2:number):Promise<Array<testrepo.AuditEntry>>;

export function ListBugsForContainer(arg1:string,arg2:string):Promise<Array<testrepo.Bug>>;

export function ListBugsWithTests(arg1:string):Promise<Array<testrepo.BugWithTests>>;

export function ListCanonicalRequirements(arg1:string):Promise<Array<coverage.CanonicalRequirement>>;

export function ListCanonicalReuse(arg1:string,arg2:string):Promise<Array<coverage.ReuseRow>>;

export function ListChangeRequests(arg1:string,arg2:string):Promise<Array<coverage.ChangeRequest>>;

export function ListComponents(arg1:string):Promise<Array<testrepo.Bucket>>;

export function ListContainers(arg1:string,arg2:string):Promise<Array<testrepo.Container>>;

export function ListCoverageCandidateTests(arg1:string,arg2:string):Promise<Array<coverage.CandidateTest>>;

export function ListCoverageGaps(arg1:string,arg2:string):Promise<Array<coverage.Gap>>;

export function ListCoverageProjects(arg1:string):Promise<Array<coverage.ProjectConfig>>;

export function ListFolders(arg1:string):Promise<Array<testrepo.Folder>>;

export function ListMatchingKeys(arg1:string,arg2:testrepo.Query):Promise<Array<string>>;

export function ListPendingChanges(arg1:string):Promise<Array<testrepo.PendingChange>>;

export function ListPreconditionsWithUsage(arg1:string):Promise<Array<testrepo.PreconditionUsage>>;

export function ListPriorities(arg1:string):Promise<Array<string>>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function ListProjectComponents(arg1:string,arg2:string):Promise<Array<string>>;

export function ListProjectFixVersions(arg1:string,arg2:string):Promise<Array<string>>;

export function ListRequirementLinkTypes(arg1:string):Promise<Array<string>>;

export function ListRequirementSources(arg1:string):Promise<Array<testrepo.RequirementSource>>;

export function ListRequirementsWithCoverage(arg1:string):Promise<Array<testrepo.RequirementCoverage>>;

export function ListSavedViews(arg1:string):Promise<Array<testrepo.SavedView>>;

export function ListStatuses(arg1:string):Promise<Array<string>>;

export function ListSyncLog(arg1:string,arg2:number):Promise<Array<testrepo.SyncLogEntry>>;

export function ListTestCallLinks(arg1:string):Promise<Array<testrepo.TestCallLink>>;

export function ListTests(arg1:string,arg2:testrepo.Query):Promise<testrepo.Page>;

export function ListTestsForBug(arg1:string,arg2:string):Promise<Array<testrepo.BugTest>>;

export function ListTestsForPrecondition(arg1:string,arg2:string):Promise<Array<testrepo.PreconditionTest>>;

export function ListTestsForRequirement(arg1:string,arg2:string):Promise<Array<testrepo.RequirementTest>>;

export function ListValueTests(arg1:string,arg2:string):Promise<Array<string>>;

export function ListVersions(arg1:string,arg2:string):Promise<Array<coverage.Version>>;

export function MoveTestToFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function PreviewImport(arg1:string,arg2:boolean):Promise<testrepo.ImportPreview>;

export function ReadLog(arg1:number):Promise<string>;

export function RecreateDeletedTest(arg1:string,arg2:string):Promise<string>;

export function RemoveRequirementSource(arg1:string,arg2:string):Promise<void>;

export function RenameCanonicalRequirement(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function RenameFolder(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameVersion(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function ReorderTestSteps(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function ResolveConflictKeepRemote(arg1:string,arg2:string):Promise<void>;

export function ResolveConflictMerge(arg1:string,arg2:string,arg3:string,arg4:Array<testrepo.ConflictDecision>):Promise<void>;

export function ResolveConflictOverride(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunStatuses():Promise<Array<string>>;

export function ScanAllDuplicateSteps(arg1:string):Promise<number>;

export function ScanDuplicateGroupSteps(arg1:string,arg2:string):Promise<testrepo.DuplicateGroup>;

export function ScanDuplicates(arg1:string):Promise<testrepo.DuplicateReport>;

export function SeedDemoCoverageExample(arg1:string):Promise<string>;

export function SeedEUICCReference(arg1:string):Promise<coverage.EUICCSeedSummary>;

export function SeedPKCS11Reference(arg1:string):Promise<coverage.PKCSSeedSummary>;

export function SeedSampleContainers(arg1:string):Promise<testrepo.SeedResult>;

export function SetCRDecision(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetCanonicalMembers(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetContainerEnvironments(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetCoverageProjects(arg1:string,arg2:Array<coverage.ProjectConfig>):Promise<void>;

export function SetDefaultProfile(arg1:string):Promise<void>;

export function SetMemberVersion(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetRequirementLinkType(arg1:string):Promise<void>;

export function SetRequirementLinks(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function SetRequirementSource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetShowCoverage(arg1:boolean):Promise<void>;

export function SetTestPreconditions(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetTestRequirements(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetTestReview(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetTestRunComment(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetTestRunStatus(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetValueTests(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SetVersionStatus(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SyncBugs(arg1:string):Promise<void>;

export function SyncContainers(arg1:string):Promise<void>;

export function SyncProfile(arg1:string):Promise<void>;

export function SyncProfileFull(arg1:string):Promise<void>;

export function SyncRequirements(arg1:string):Promise<void>;

export function SyncTestCalls(arg1:string):Promise<void>;

export function SyncTests(arg1:string):Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function TestProfileConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function TransitionTest(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UnexcludeFromDuplicates(arg1:string,arg2:string):Promise<void>;

export function UnlinkBugFromRun(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateChangeRequest(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function UpdateProfile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:boolean):Promise<profile.Profile>;

export function UpdateProfileScope(arg1:string,arg2:string):Promise<void>;

export function UpdateProfileToken(arg1:string,arg2:string):Promise<void>;

export function UpsertCoverageNode(arg1:string,arg2:coverage.NodeEdit):Promise<string>;
